[package]
name = "schemafy"
version = "0.1.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
build = "build.rs"

description = "Generates serializeable Rust types from a json schema"
license = "MIT"

repository = "https://github.com/Marwes/schemafy"
documentation = "https://docs.rs/schemafy"

[workspace]

[dependencies]
quote = "0.3"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

Inflector = "0.6.0"

[build-dependencies]
schemafy_snapshot = { version = "0.1.0", path = "schemafy_snapshot" }

[features]
default = ["rustfmt"]
rustfmt = []
