[package]
name = "schemafy"
version = "0.3.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
build = "build.rs"

description = "Generates serializeable Rust types from a json schema"
license = "MIT"

repository = "https://github.com/Marwes/schemafy"
documentation = "https://docs.rs/schemafy"

[workspace]

[dependencies]
quote = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

Inflector = "0.6.0"
itertools = "0.5.9"

[build-dependencies]
schemafy_snapshot = { version = "0.3.0", path = "schemafy_snapshot" }
