[package]
name = "schemafy"
version = "0.5.0" # VERSION_TAG
authors = ["Markus Westerlind <marwes91@gmail.com>"]
edition = "2018"

description = "Generates serializeable Rust types from a json schema"
license = "MIT"

repository = "https://github.com/Marwes/schemafy"
documentation = "https://docs.rs/schemafy"

default-run = "main"

[lib]
proc-macro = true

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "generate-tests"
path = "src/generate_tests.rs"

[workspace]

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
schemafy_core = { version = "0.5.0", path = "schemafy_core" } # VERSION_TAG
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
syn = "0.15"

Inflector = "0.11"


[features]
internal-regenerate = []
