[package]
name = "schemafy"
version = "0.4.5"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
build = "build.rs"

description = "Generates serializeable Rust types from a json schema"
license = "MIT"

repository = "https://github.com/Marwes/schemafy"
documentation = "https://docs.rs/schemafy"

[lib]
proc-macro = true


[workspace]

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
schemafy_helper = { version = "0.4", path = "schemafy_helper" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
syn = "0.15"

Inflector = "0.11"

[build-dependencies]
schemafy_snapshot = { version = "0.4.0", path = "schemafy_snapshot" }
